name: Erlang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24.x
        rebar3-version: 3.16.1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Compile code
      run: make compile

    - name: Run tests
      run: make test
